MPICC   =       mpifccpx
CFLAGS  = -DFJ_MPI -O3 -Xg

all: simple-mpi simple-single

simple-mpi: simple.c
	$(MPICC) $(CFLAGS) -DMPI -o simple-mpi simple.c
simple-single: simple.c
	$(MPICC) $(CFLAGS) -o simple-single simple.c

#
# For x86 Linux
#MPICC = mpicc
#CFLAGS  = -O3 -Wall
#	mkdir -p ./darshan/`date +%Y/%m/%d | sed -e "s/\/0/\//g"`
#	export LD_PRELOAD=./libdarshan.so; export DARSHAN_HISTORY_RW="w"; mpirun -np 2 ./simple wdata
#

