#!/bin/bash
#
# $ cd darshan-2.3.0/darshan-runtime
# $ ./configure --host=x86_64-unknown-linux-gnu \
#  --target=sparc64v-sparc-linux-gnu --with-mem-align=8 \
#  --with-log-path=../darshan --with-jobid-env=NONE \
#  CC="mpifccpx -Xg" CFLAGS="-O2 -g -DHISTORY -DHISTORY_CALLER -DK_SUPERCOMPUTER -DUSE_TSC"
# $ make
# $ cd darshan-2.3.0/darshan-util
# $ ./configure CC=cc CFLAGS="-DHISTORY -DHISTORY_CALLER"
# $ make
# $ cd python/mp_test/lib
# $ qsub run-compile-k.sh
# $ make clean
#
DIST_TAR=darshan-riken-bin-`date +%Y%m%d`.tar.gz
DIST_TMPDIR=dist-darshan
DIST_DIR=darshan
DIST_WORKDIR=$DIST_TMPDIR/$DIST_DIR
mkdir -p $DIST_WORKDIR/k-lib
mkdir -p $DIST_WORKDIR/bin
mkdir -p $DIST_WORKDIR/example
mkdir -p $DIST_WORKDIR/python
cp -p README-riken.txt $DIST_WORKDIR/
cp -p darshan-2.3.0/darshan-runtime/lib/libdarshan.so $DIST_WORKDIR/k-lib/
cp -p darshan-2.3.0/darshan-runtime/lib/libdarshan-single.so $DIST_WORKDIR/k-lib/
cp -p darshan-2.3.0/darshan-util/darshan-parser $DIST_WORKDIR/bin/
cp -p darshan-2.3.0/darshan-util/darshan-history.pl $DIST_WORKDIR/bin/
cp -p example/Makefile.example $DIST_WORKDIR/example/Makefile
cp -p example/run-k-single.sh $DIST_WORKDIR/example/
cp -p example/run-k-mpi.sh $DIST_WORKDIR/example/
cp -p example/run-k-ccode.sh $DIST_WORKDIR/example/
cp -p example/simple.c $DIST_WORKDIR/example/
cp -p example/ccode.c $DIST_WORKDIR/example/
cp -p example/ccode-func.c $DIST_WORKDIR/example/
cp -rp python $DIST_WORKDIR
rm -f $DIST_WORKDIR/mp_test/MEMO
rm -f $DIST_WORKDIR/mp_test/Makefile
mv  $DIST_WORKDIR/mp_test/Makefile.dist $DIST_WORKDIR/mp_test/Makefile
(cd $DIST_TMPDIR; tar czf $DIST_TAR $DIST_DIR; mv $DIST_TAR ../)
/bin/rm -rf $DIST_TMPDIR
