#!/bin/bash
#
DARSHAN=darshan-2.3.0
DIST_TAR=darshan-riken-source-`date +%Y%m%d`.tar.gz
DIST_TMPDIR=dist-darshan-riken
DIST_DIR=darshan-riken
#
DIST_WORKDIR=$DIST_TMPDIR/$DIST_DIR
mkdir -p $DIST_WORKDIR/
mkdir -p $DIST_WORKDIR/example
mkdir -p $DIST_WORKDIR/python
cp -rp  $DARSHAN $DIST_WORKDIR/
(cd $DIST_WORKDIR/darshan-2.3.0; rm -f MEMO*)
(cd $DIST_WORKDIR/darshan-2.3.0/darshan-runtime; make clean)
(cd $DIST_WORKDIR/darshan-2.3.0/darshan-util; make clean)
cp -p INSTALL-riken.txt $DIST_WORKDIR/
cp -p README-riken.txt $DIST_WORKDIR/
cp -p example/Makefile.example $DIST_WORKDIR/example/Makefile
cp -p example/run-k-mpi.sh $DIST_WORKDIR/example/
cp -p example/run-k-single.sh $DIST_WORKDIR/example/
cp -p example/run-k-ccode.sh $DIST_WORKDIR/example/
cp -p example/simple.c $DIST_WORKDIR/example/
cp -p example/ccode.c $DIST_WORKDIR/example/
cp -p example/ccode-func.c $DIST_WORKDIR/example/
cp -p example/stream3.c $DIST_WORKDIR/example/stream.c
cp -rp python $DIST_WORKDIR
rm -f $DIST_WORKDIR/python/mp_test/MEMO
rm -f $DIST_WORKDIR/python/mp_test/Makefile.dist
#
(cd $DIST_TMPDIR; tar czf $DIST_TAR $DIST_DIR)
mv $DIST_TMPDIR/$DIST_TAR ./
rm -rf $DIST_TMPDIR
